//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionSchedule
    {
        public int Id_Schedule { get; set; }
        public int Id_Competence { get; set; }
        public int Id_ChiefExpert { get; set; }
        public int Id_MentorExpert { get; set; }
        public int Id_TechnicalExpert { get; set; }
        public System.DateTime MainGroupStartDate { get; set; }
        public System.DateTime MainGroupEndDate { get; set; }
        public System.DateTime JuniorStartDate { get; set; }
        public System.DateTime JuniorEndDate { get; set; }
    
        public virtual Expert Expert { get; set; }
        public virtual Competences Competences { get; set; }
        public virtual Expert Expert1 { get; set; }
        public virtual Expert Expert2 { get; set; }
    }
}
