//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expert()
        {
            this.ChampionSchedule = new HashSet<ChampionSchedule>();
            this.ChampionSchedule1 = new HashSet<ChampionSchedule>();
            this.ChampionSchedule2 = new HashSet<ChampionSchedule>();
        }
    
        public int Id_Expert { get; set; }
        public string SurnameExpert { get; set; }
        public string NameExpert { get; set; }
        public string PatronymicExpert { get; set; }
        public string EmailExpert { get; set; }
        public string PhoneNumberExpert { get; set; }
        public string RegionExpert { get; set; }
        public string CountryExpert { get; set; }
        public int Id_Organization { get; set; }
        public int Id_ClothingSizeExpert { get; set; }
        public int Id_Role { get; set; }
        public int Id_Competence { get; set; }
    
        public virtual ClothingSizes ClothingSizes { get; set; }
        public virtual Competences Competences { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual ExpertRole ExpertRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChampionSchedule> ChampionSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChampionSchedule> ChampionSchedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChampionSchedule> ChampionSchedule2 { get; set; }

        // Добавленное свойство для отображения полного имени эксперта
        public string FullName
        {
            get { return $"{SurnameExpert} {NameExpert} {PatronymicExpert}"; }
        }
    }
}
