//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Junior
    {
        public int Id_Junior { get; set; }
        public string SurnameJunior { get; set; }
        public string NameJunior { get; set; }
        public string PatronymicJunior { get; set; }
        public string EmailJunior { get; set; }
        public string PhoneNumberJunior { get; set; }
        public string RegionJunior { get; set; }
        public string CountryJunior { get; set; }
        public int Id_Organization { get; set; }
        public int Id_ClothingSizeJunior { get; set; }
        public int Id_Category { get; set; }
        public int Id_Competence { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ClothingSizes ClothingSizes { get; set; }
        public virtual Competences Competences { get; set; }
        public virtual Organizations Organizations { get; set; }
    }
}
